name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main # 如果妳的主分支叫 master，請改成 master

jobs:
  web-deploy:
    name: 🎉 上架至免費雲端主機
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 讀取 GitHub 最新原始碼
      uses: actions/checkout@v3

    - name: 🚀 透過自動化 FTP 同步到 public_html
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: htdocs/ # InfinityFree 的網頁根目錄
